//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravianBot.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravianBot.Ressources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;l2&apos;].
        /// </summary>
        internal static string id_clay {
            get {
                return ResourceManager.GetString("id_clay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;l3&apos;].
        /// </summary>
        internal static string id_iron {
            get {
                return ResourceManager.GetString("id_iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;l4&apos;].
        /// </summary>
        internal static string id_wheat {
            get {
                return ResourceManager.GetString("id_wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;l1&apos;].
        /// </summary>
        internal static string id_wood {
            get {
                return ResourceManager.GetString("id_wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string login_username {
            get {
                return ResourceManager.GetString("login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to build.php?id=31.
        /// </summary>
        internal static string url_barracks {
            get {
                return ResourceManager.GetString("url_barracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dorf2.php.
        /// </summary>
        internal static string url_building {
            get {
                return ResourceManager.GetString("url_building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position_details.php?.
        /// </summary>
        internal static string url_gridCell {
            get {
                return ResourceManager.GetString("url_gridCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to karte.php.
        /// </summary>
        internal static string url_map {
            get {
                return ResourceManager.GetString("url_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to build.php?tt=2&amp;id=39.
        /// </summary>
        internal static string url_rallyPoint_sendTroops {
            get {
                return ResourceManager.GetString("url_rallyPoint_sendTroops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dorf1.php?newdid=56449&amp;.
        /// </summary>
        internal static string url_ressources_Praven {
            get {
                return ResourceManager.GetString("url_ressources_Praven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dorf1.php?newdid=71545&amp;.
        /// </summary>
        internal static string url_ressources_Suno {
            get {
                return ResourceManager.GetString("url_ressources_Suno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to build.php?id=23.
        /// </summary>
        internal static string url_stables {
            get {
                return ResourceManager.GetString("url_stables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troops&quot;]/tbody/tr[1]/td[1]/a.
        /// </summary>
        internal static string XPath_all_legionnaires {
            get {
                return ResourceManager.GetString("XPath_all_legionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;build&quot;]/div[2]/form/table[2]/tbody[2]/tr/td/div[1].
        /// </summary>
        internal static string XPath_arrival_time {
            get {
                return ResourceManager.GetString("XPath_arrival_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;nonFavouriteTroops&quot;]/div[1]/div/div[2]/div[4]/a.
        /// </summary>
        internal static string XPath_buyAllLegionnaire {
            get {
                return ResourceManager.GetString("XPath_buyAllLegionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;nonFavouriteTroops&quot;]/div[5]/div/div[2]/div[4]/input.
        /// </summary>
        internal static string XPath_buyXEquitesImperatoris {
            get {
                return ResourceManager.GetString("XPath_buyXEquitesImperatoris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;nonFavouriteTroops&quot;]/div[3]/div/div[2]/div[5]/input.
        /// </summary>
        internal static string XPath_buyXImperian {
            get {
                return ResourceManager.GetString("XPath_buyXImperian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;nonFavouriteTroops&quot;]/div[1]/div/div[2]/div[4]/input.
        /// </summary>
        internal static string XPath_buyXLegionnaire {
            get {
                return ResourceManager.GetString("XPath_buyXLegionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;btn_ok&quot;].
        /// </summary>
        internal static string XPath_ConfirmBtn {
            get {
                return ResourceManager.GetString("XPath_ConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troops&quot;]/tbody/tr[2]/td[2]/input.
        /// </summary>
        internal static string XPath_EquitesImperatoris {
            get {
                return ResourceManager.GetString("XPath_EquitesImperatoris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;build&quot;]/div[2]/p.
        /// </summary>
        internal static string XPath_error_sending_troops {
            get {
                return ResourceManager.GetString("XPath_error_sending_troops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troops&quot;]/tbody/tr[3]/td[4]/input.
        /// </summary>
        internal static string XPath_hero {
            get {
                return ResourceManager.GetString("XPath_hero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troops&quot;]/tbody/tr[3]/td[1]/input.
        /// </summary>
        internal static string XPath_Imperian {
            get {
                return ResourceManager.GetString("XPath_Imperian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;movements&quot;]/tbody/tr[1]/th.
        /// </summary>
        internal static string XPath_IncomingTroops_section {
            get {
                return ResourceManager.GetString("XPath_IncomingTroops_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;movements&quot;]/tbody/tr[2]/td[2]/div[1]/span.
        /// </summary>
        internal static string XPath_IncomingTroops_span {
            get {
                return ResourceManager.GetString("XPath_IncomingTroops_span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;movements&quot;]/tbody/tr[2]/td[2]/div[2]/span.
        /// </summary>
        internal static string Xpath_IncomingTroops_time {
            get {
                return ResourceManager.GetString("Xpath_IncomingTroops_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troops&quot;]/tbody/tr[1]/td[1]/input.
        /// </summary>
        internal static string XPath_legionnaire {
            get {
                return ResourceManager.GetString("XPath_legionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troops&quot;]/tbody/tr[1]/td[1]/a.
        /// </summary>
        internal static string XPath_legionnaireAmount {
            get {
                return ResourceManager.GetString("XPath_legionnaireAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;sidebarBoxVillagelist&quot;]/div[2]/div[2]/ul/li[2]/a.
        /// </summary>
        internal static string XPath_MainVillage {
            get {
                return ResourceManager.GetString("XPath_MainVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;build&quot;]/div[2]/p.
        /// </summary>
        internal static string XPath_noVillage_msg {
            get {
                return ResourceManager.GetString("XPath_noVillage_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troop_info&quot; and @class=&quot;transparent&quot;]/tbody/tr[1].
        /// </summary>
        internal static string XPath_oasis_troops {
            get {
                return ResourceManager.GetString("XPath_oasis_troops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;btn_ok&quot;].
        /// </summary>
        internal static string XPath_OkBtn {
            get {
                return ResourceManager.GetString("XPath_OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troops&quot;]/tbody/tr[2]/td[1]/input.
        /// </summary>
        internal static string XPath_Praetorian {
            get {
                return ResourceManager.GetString("XPath_Praetorian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;build&quot;]/div[2]/form/div[2]/label[3]/input.
        /// </summary>
        internal static string XPath_raid {
            get {
                return ResourceManager.GetString("XPath_raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troops&quot;]/tbody/tr[2]/td[4]/input.
        /// </summary>
        internal static string XPath_Settlers {
            get {
                return ResourceManager.GetString("XPath_Settlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;s1&quot;].
        /// </summary>
        internal static string XPath_train_troops {
            get {
                return ResourceManager.GetString("XPath_train_troops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;troops&apos;]/tbody/tr[1].
        /// </summary>
        internal static string XPath_troops_row_one {
            get {
                return ResourceManager.GetString("XPath_troops_row_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troops&quot;]/tbody/tr[2].
        /// </summary>
        internal static string XPath_troops_row_two {
            get {
                return ResourceManager.GetString("XPath_troops_row_two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;troops&quot;]/tbody/tr.
        /// </summary>
        internal static string XPath_troops_rows {
            get {
                return ResourceManager.GetString("XPath_troops_rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;sidebarBoxVillagelist&quot;]/div[2]/div[2]/ul.
        /// </summary>
        internal static string XPath_VillageList {
            get {
                return ResourceManager.GetString("XPath_VillageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;xCoordInput&quot;].
        /// </summary>
        internal static string XPath_x_coord {
            get {
                return ResourceManager.GetString("XPath_x_coord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;yCoordInput&quot;].
        /// </summary>
        internal static string XPath_y_coord {
            get {
                return ResourceManager.GetString("XPath_y_coord", resourceCulture);
            }
        }
    }
}
